### ISSUE TITLE
micStream.track is not working

### ISSUE THREAD

**Issue by soham24** [videosdk-live/videosdk-rtc-react-sdk-example#16]
![Screenshot 2022-08-01 at 3 29 43 PM](https://user-images.githubusercontent.com/1888767/182124621-38658a62-9f0b-41be-b283-d5bcc59da7bf.png)

**Comment by rajansurani** [comment]
@soham24 We have updated the code sample Please check now.

**Comment by soham24** [comment]
@rajansurani thank you for quick response 
it is working now
