### ISSUE TITLE
Mozilla Firefox Camera support

### ISSUE THREAD

**Issue by og1sha** [videosdk-live/videosdk-rtc-react-sdk-example#2]
I have tried running this example in Mozilla Firefox browser (version 93.0 (64-bit)) and camera is not starting up. I can use my microphone and I can see feeds from other participants. Google chrome and Edge browsers are working fine. Do I need to add some additional configuration code for Firefox?

I have noticed that property webcamOn (coming from useParticipant hook) is always false:
```
const {    
    webcamStream,    
    micStream,    
    webcamOn, //this one is always false for Firefox
    micOn,
    isLocal,
    isActiveSpeaker,
    participant

  } = useParticipant(participantId, {
    onStreamEnabled,
    onStreamDisabled,
  })
```

**Comment by arjun-kava** [comment]
Hey, @og1sha. Let us review this and get back to you. I'll try to reproduce it from my end

**Comment by arjun-kava** [comment]
Hey, This is fixed in the newer version. Thanks,
