### ISSUE TITLE
changeWebcam not working on Android Chrome and Firefox

### ISSUE THREAD

**Issue by og1sha** [videosdk-live/videosdk-rtc-react-sdk-example#3]
Latest versions of browsers Mozilla Firefox and Google Chrome (not sure about others, only these were tested) on device Google pixel 3a do not work when switching to another video device using changeWebcam method specified on https://docs.videosdk.live/docs/realtime-communication/sdk-reference/react-sdk/use-meeting

`changeWebcam(deviceId: string)function`

I have tried using this method (returned from useMeeting hook) but with no luck. As a parameter I am passing correct device ID of the back mobile camera. Instead of new video feed from second camera, current feed goes blank and it is no longer available in the meeting session.

**Comment by arjun-kava** [comment]
Hey, @og1sha it is fixed in a newer version of SDK. Please update. Thanks.
